@echo off
setlocal enabledelayedexpansion
echo 青花瓷| curl -I --connect-timeout 5 "https://npm.elemecdn.com/anzhiyu-music@1.0.4/青花瓷/青花瓷.mp3" 2>nul | findstr "HTTP" 
echo 稻香| curl -I --connect-timeout 5 "https://npm.elemecdn.com/anzhiyu-music@1.0.1/周杰伦/稻香/稻香.mp3" 2>nul | findstr "HTTP"
echo 晴天| curl -I --connect-timeout 5 "https://npm.elemecdn.com/anzhiyu-music@1.0.2/晴天/晴天.mp3" 2>nul | findstr "HTTP"
echo 七里香| curl -I --connect-timeout 5 "https://npm.elemecdn.com/anzhiyu-music@1.0.2/七里香/七里香.mp3" 2>nul | findstr "HTTP"
echo 花海| curl -I --connect-timeout 5 "https://npm.elemecdn.com/anzhiyu-music-jay@1.0.1/花海/花海.flac" 2>nul | findstr "HTTP"
echo 反方向的钟| curl -I --connect-timeout 5 "https://npm.elemecdn.com/anzhiyu-music-jay@1.0.1/反方向的钟/反方向的钟.flac" 2>nul | findstr "HTTP"
echo 兰亭序| curl -I --connect-timeout 5 "https://npm.elemecdn.com/anzhiyu-music@1.0.1/周杰伦/兰亭序/兰亭序.mp3" 2>nul | findstr "HTTP"
echo 说好的辛福呢| curl -I --connect-timeout 5 "https://npm.elemecdn.com/anzhiyu-music@1.0.2/说好的辛福呢/说好的辛福呢.mp3" 2>nul | findstr "HTTP"
echo 等你下课| curl -I --connect-timeout 5 "https://npm.elemecdn.com/anzhiyu-music@1.0.1/周杰伦/等你下课/等你下课.mp3" 2>nul | findstr "HTTP"
echo 我落泪情绪零碎| curl -I --connect-timeout 5 "https://npm.elemecdn.com/anzhiyu-music@1.0.2/我落泪情绪零碎/我落泪情绪零碎.mp3" 2>nul | findstr "HTTP"
echo 听妈妈的话| curl -I --connect-timeout 5 "https://npm.elemecdn.com/anzhiyu-music@1.0.2/听妈妈的话/听妈妈的话.mp3" 2>nul | findstr "HTTP"
echo 明明就| curl -I --connect-timeout 5 "https://npm.elemecdn.com/anzhiyu-music-jay@1.0.1/明明就/明明就.flac" 2>nul | findstr "HTTP"
echo 我是如此相信| curl -I --connect-timeout 5 "https://npm.elemecdn.com/anzhiyu-music-jay@1.0.1/我是如此相信/我是如此相信.flac" 2>nul | findstr "HTTP"
echo 发如雪| curl -I --connect-timeout 5 "https://npm.elemecdn.com/anzhiyu-music@1.0.3/发如雪/发如雪.mp3" 2>nul | findstr "HTTP"
echo 以父之名| curl -I --connect-timeout 5 "https://npm.elemecdn.com/anzhiyu-music@1.0.3/以父之名/以父之名.mp3" 2>nul | findstr "HTTP"
echo 园游会| curl -I --connect-timeout 5 "https://npm.elemecdn.com/anzhiyu-music@1.0.3/园游会/园游会.flac" 2>nul | findstr "HTTP"
echo 本草纲目| curl -I --connect-timeout 5 "https://npm.elemecdn.com/anzhiyu-music@1.0.4/本草纲目/本草纲目.mp3" 2>nul | findstr "HTTP"
echo 龙卷风| curl -I --connect-timeout 5 "https://npm.elemecdn.com/anzhiyu-music@1.0.4/龙卷风/龙卷风.mp3" 2>nul | findstr "HTTP"